### ISSUE TITLE
Dealing with missing data in blavaan

### ISSUE THREAD

**Issue by littlehifive** [ecmerkle/blavaan#39] opened 2021-10-03 17:55 UTC
Hi sorry I am not sure if this is a good question to ask on GitHub, but professor Ben Goodrich suggested that I reach out to the authors (see my original StackOverflow post [here](https://stackoverflow.com/questions/69336008/how-to-deal-with-missing-data-using-blavaan)).

I am trying to run Bayesian SEM on my data using `bsem` in `blavaan`. However, it doesn't seem like it has arguments like `missing = "FIML"` as in the case of the `lavaan` package. **What would be the best practice of dealing with missingness other than list-wise deletion?**

This is the paragraph where Garnier-Villarreal and Jorgensen (2020) talked about handling missing data, but I am not sure how exactly I should actualize their recommendations: "While it is often useful and desirable to directly model the missing values with the rest of the model (e.g., Merkle 2011; O’Muircheartaigh and Moustaki 1999), blavaan employs a "missing at random" approach to missing data that differs across JAGS and Stan. In JAGS, one can include NA values in the data, and JAGS will sample these missing values as if they were extra model parameters. In contrast, Stan does not allow NA values in the data, so that one must handle the missing data manually. We utilize a "full information" likelihood (e.g., Wothke 2000) in our Stan models, which is the same likelihood that is used to handle missing data in lavaan and other software that performs maximum likelihood SEM estimation. This requires some additional overhead in preparing the data to be sent to Stan, because each case's observed values must be indexed, and cases are sorted by missing data pattern to speed up computations. Missing values could also be directly sampled ("imputed") in Stan, though this functionality is not currently available."

Thank you!

**Comment by ecmerkle** [comment] 2021-10-04 03:57
I just answered it on StackOverflow. The short answer is that you automatically get "FIML" when you have missing data in blavaan.

**Comment by littlehifive** [comment] 2021-10-06 19:27
Yes you are right! When I removed the rows with all missingness, the model ran without error. Here is my sessionInfo just in case it is a bug:

```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: OS X Snow Leopard 11.6

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] blavaan_0.3-17     RcppParallel_5.1.4 Rcpp_1.0.7         semPlot_1.1.2      semTools_0.5-4     tidySEM_0.1.10    
 [7] lavaan_0.6-9       kableExtra_1.3.4   lme4_1.1-27.1      Matrix_1.3-4       forcats_0.5.1      stringr_1.4.0     
[13] dplyr_1.0.7        purrr_0.3.4        readr_2.0.2        tidyr_1.1.4        tibble_3.1.5       ggplot2_3.3.5     
[19] tidyverse_1.3.1   

loaded via a namespace (and not attached):
  [1] utf8_1.2.2            proto_1.0.0           tidyselect_1.1.1      htmlwidgets_1.5.4     grid_4.0.2           
  [6] munsell_0.5.0         codetools_0.2-18      future_1.21.0         withr_2.4.2           colorspace_2.0-2     
 [11] OpenMx_2.19.8         knitr_1.36            rstudioapi_0.13       stats4_4.0.2          bayesplot_1.8.1      
 [16] listenv_0.8.0         mi_1.0                emmeans_1.6.1         rstan_2.21.2          repr_1.1.3           
 [21] mnormt_2.0.2          MCMCpack_1.5-0        bit64_4.0.5           rprojroot_2.0.2       parallelly_1.26.0    
 [26] coda_0.19-4           vctrs_0.3.8           generics_0.1.0        TH.data_1.0-10        xfun_0.26            
 [31] R6_2.5.1              arm_1.11-2            assertthat_0.2.1      vroom_1.5.5           scales_1.1.1         
 [36] multcomp_1.4-17       nnet_7.3-16           texreg_1.37.5         gtable_0.3.0          globals_0.14.0       
 [41] conquer_1.0.2         processx_3.5.2        mcmc_0.9-7            sandwich_3.0-1        rlang_0.4.11         
 [46] MatrixModels_0.5-0    systemfonts_1.0.2     splines_4.0.2         broom_0.7.8           checkmate_2.0.0      
 [51] inline_0.3.19         yaml_2.2.1            reshape2_1.4.4        abind_1.4-5           modelr_0.1.8         
 [56] backports_1.2.1       Hmisc_4.5-0           tools_4.0.2           psych_2.1.9           ellipsis_0.3.2       
 [61] RColorBrewer_1.1-2    Rsolnp_1.16           ggridges_0.5.3        gsubfn_0.7            plyr_1.8.6           
 [66] base64enc_0.1-3       prettyunits_1.1.1     rockchalk_1.8.144     ps_1.6.0              rpart_4.1-15         
 [71] pbapply_1.5-0         zoo_1.8-9             qgraph_1.6.9          haven_2.4.3           cluster_2.1.2        
 [76] fs_1.5.0              here_1.0.1            magrittr_2.0.1        data.table_1.14.2     nonnest2_0.5-5       
 [81] openxlsx_4.2.4        SparseM_1.81          reprex_2.0.0          truncnorm_1.0-8       tmvnsim_1.0-2        
 [86] mvtnorm_1.1-2         matrixcalc_1.0-5      matrixStats_0.59.0    hms_1.1.1             evaluate_0.14        
 [91] xtable_1.8-4          XML_3.99-0.8          jpeg_0.1-9            readxl_1.3.1          rstantools_2.1.1     
 [96] fastDummies_1.6.3     gridExtra_2.3         compiler_4.0.2        V8_3.4.2              crayon_1.4.1         
[101] StanHeaders_2.21.0-7  minqa_1.2.4           htmltools_0.5.2       corpcor_1.6.10        tzdb_0.1.2           
[106] Formula_1.2-4         lubridate_1.7.10      DBI_1.1.1             kutils_1.70           dbplyr_2.1.1         
[111] MASS_7.3-54           boot_1.3-28           cli_3.0.1             parallel_4.0.2        insight_0.14.2       
[116] igraph_1.2.6          pkgconfig_2.0.3       sem_3.1-11            foreign_0.8-81        skimr_2.1.3          
[121] xml2_1.3.2            pbivnorm_0.6.0        svglite_2.0.0         webshot_0.5.2         estimability_1.3     
[126] CompQuadForm_1.4.3    rvest_1.0.0           callr_3.7.0           digest_0.6.28         rmarkdown_2.11       
[131] cellranger_1.1.0      htmlTable_2.2.1       lisrelToR_0.1.4       curl_4.3.2            gtools_3.9.2         
[136] quantreg_5.86         nloptr_1.2.2.2        lifecycle_1.0.1       nlme_3.1-152          glasso_1.11          
[141] jsonlite_1.7.2        carData_3.0-4         viridisLite_0.4.0     fansi_0.5.0           pillar_1.6.3         
[146] loo_2.4.1             lattice_0.20-44       fastmap_1.1.0         httr_1.4.2            pkgbuild_1.2.0       
[151] survival_3.2-11       glue_1.4.2            zip_2.2.0             fdrtool_1.2.16        MplusAutomation_1.0.0
[156] png_0.1-7             bit_4.0.4             pander_0.6.4          stringi_1.7.5         regsem_1.8.0         
[161] latticeExtra_0.6-29   future.apply_1.8.1   
```

**Comment by ecmerkle** [comment] 2023-07-03 15:33
Thanks for the report! The github version is a bit unstable right now because I am in the middle of adding some multilevel functionality. Can you reproduce the issue with the CRAN version (0.4-8), which is also commit 6713f92?

**Comment by ecmerkle** [comment] 2023-07-07 21:25
I had a bit more of a look and see that it is happening on a call to lavaan prior to blavaan estimation. Am re-opening to see what is happening.

**Comment by ecmerkle** [comment] 2023-07-11 15:19
Have not found the problem, but I think it is informative that `cfa()` from lavaan leads to the same error, even if you set `do.fit = FALSE`.

**Comment by albertostefanelli** [comment] 2023-07-11 15:24
found the source of this error. There is a group in the data with only 1 observation after NAs deletion. Unfortunately, neither lavaan or blavaan correctly report this (in other situations they correctly do). Feel free to close the issue and sorry for the trouble.

**Comment by ecmerkle** [comment] 2023-07-11 15:31
Thanks for the update, and I will at least try to get an error message reported here.

**Comment by ecmerkle** [comment] 2023-07-12 16:23
This should be addressed with pull request 286 in the lavaan repo.

**Closed by ecmerkle** 2023-07-12 16:23 UTC
